#!/bin/sh

lb config noauto \
	--apt-indices "false" \
	--apt-recommends "false" \
	--apt-secure "false" \
	--apt-source-archives "false" \
	--architectures "i386" \
	--archive-areas "main" \
	--backports "false" \
	--binary-images "iso-hybrid" \
	--bootloader "syslinux" \
	--cache "false" \
	--cache-indices "false" \
	--cache-packages "false" \
	--clean \
	--checksums "md5" \
	--debian-installer "false" \
	--debug \
	--distribution "wheezy" \
	--hostname "mate" \
	--linux-flavours "686-pae" \
	--linux-packages "linux-image" \
	--memtest "none" \
	--mirror-binary "http://localhost:9999/debian/" \
	--mirror-bootstrap "http://localhost:9999/debian/" \
	--package-lists "minimal" \
	--parent-archive-areas "main" \
	--parent-distribution "wheezy" \
	--parent-mirror-binary "http://localhost:9999/debian/" \
	--parent-mirror-bootstrap "http://localhost:9999/debian/" \
	--security "false" \
	--source "false" \
	--verbose \
	--volatile "false" \
	"${@}"
